### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by lukeidiot** [AkashKarnatak/Ajnabee#1]
Hey, I'm actively trying to improve this app, could we collab via email or messenger? Email: lukeidiot@gmail.com

**Comment by AkashKarnatak** [comment]
I'd like to hear from you, can you message me on discord. shinsatomasumi#0

**Comment by lukeidiot** [comment]
i tried to add you on discord, but it didnt exist, add: lukeidiot on discord

**Comment by AkashKarnatak** [comment]
@lukeidiot I created a discord server. https://discord.gg/BUQe4bzB
