### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LiamSirBean** [AkashKarnatak/Ajnabee#4]
Can you have the environment variables already in the code because Im confused where to put everything.

**Comment by lukeidiot** [comment]
If you don't know this basic info, maybe coding isnt for you lol

**Comment by AkashKarnatak** [comment]
Try following the instructions in the README and you should be good to go.

**Comment by lukeidiot** [comment]
> Try following the instructions in the README and you should be good to go.

Can you resend discord id? the one you sent was wrong, or add lukeidiot , ty

**Comment by AkashKarnatak** [comment]
@lukeidiot Your discord id isn't valid as it need have an identifier as well (number that follows hashtag), so I sent you an email

**Comment by exnfox** [comment]
~/Ajnabee$ npm run dev
\
> Ajnabee@1.0.0 dev
> nodemon app.js -e js,html,css

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,html,css
[nodemon] starting `node app.js`
file:///home/dillon/Ajnabee/db/sqlite.js:29
await db.init()
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lukeidiot** [comment]
> @lukeidiot Your discord id isn't valid as it needs to have an identifier as well (number that follows hashtag), so I sent you an email yesterday

I never got your email
